name: Daily snapshot

on:
  schedule:
  - cron: '0 4 * * *'   # run every day at 4 AM
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn install
    - run: yarn run snapshot
